# Video Routes

GET http://localhost:4000/api/videos

###

POST http://localhost:4000/api/videos
Content-Type: application/json

{
    "name" :"Earth Machine Top 16 EUWCQ 2023",
    "videoURL" : "https://www.youtube.com/watch?v=guz65FfByaA",
    "store": "64da30ddaf9ff86e08954c8f"
}
###

POST http://localhost:4000/api/videos
Content-Type: application/json

{
    "name" :"Undefeated Vanquish Soul",
    "videoURL" : "https://www.youtube.com/watch?v=tQabL1Ua9bQ",
    "store": "64da30ddaf9ff86e08954c8f"
}
###


POST http://localhost:4000/api/videos
Content-Type: application/json

{
    "name" :"Top 5 Beginner Decks to Try (Yugioh)",
    "videoURL" : "https://www.youtube.com/watch?v=sTEt0-ER4gA",
    "store": "64da30ddaf9ff86e08954c8f"
}
###


POST http://localhost:4000/api/videos
Content-Type: application/json

{
    "name" :"Samsung Z Flip 5",
    "videoURL" : "https://www.youtube.com/watch?v=WuljKartv2U",
    "store": "64da311baf9ff86e08954c90"
}
###


POST http://localhost:4000/api/videos
Content-Type: application/json

{
    "name" :"5 Rekomendasi KURSI GAMING Murah",
    "videoURL" : "https://www.youtube.com/watch?v=vNgROuLopas",
    "store": "64da311baf9ff86e08954c90"
}

###
POST POST http://localhost:4000/api/videos/multiple
Content-Type: application/json

{
    [
    {
    "name" :"Earth Machine Top 16 EUWCQ 2023",
    "videoURL" : "https://www.youtube.com/watch?v=guz65FfByaA",
    "store": "64da30ddaf9ff86e08954c8f"
    },
    {
    "name" :"Undefeated Vanquish Soul",
    "videoURL" : "https://www.youtube.com/watch?v=tQabL1Ua9bQ",
    "store": "64da30ddaf9ff86e08954c8f"
    },
    {
    "name" :"Top 5 Beginner Decks to Try (Yugioh)",
    "videoURL" : "https://www.youtube.com/watch?v=sTEt0-ER4gA",
    "store": "64da30ddaf9ff86e08954c8f"
    },
    {
    "name" :"Samsung Z Flip 5",
    "videoURL" : "https://www.youtube.com/watch?v=WuljKartv2U",
    "store": "64da311baf9ff86e08954c90"
    },
    {
    "name" :"5 Rekomendasi KURSI GAMING Murah",
    "videoURL" : "https://www.youtube.com/watch?v=vNgROuLopas",
    "store": "64da311baf9ff86e08954c90"
    }
]}
###
PATCH  http://localhost:4000/api/videos/view/64da32475236b58d030f982a
Content-Content-Type: application/json

###

GET http://localhost:4000/api/comments/1

###
POST http://localhost:4000/api/comments/1
Content-Type: application/json

{
    "username" : "banannaman",
    "videoURL" : "1",
    "comment": "Pm Gan"
}